name: weaver CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Android SDK
        uses: flutter/setup-android-sdk@v2
        with:
          components: 'platform-tools,build-tools-30.0.3'
          licenses: 'android-sdk-preview-license-.+'
          sdk_root: /usr/local/android-sdk

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run tests
        run: ./gradlew test

      - name: Check code quality
        run: ./gradlew check

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
