name: Weaver CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Test
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleDebug test
          
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Linting
        run: ./gradlew lint

  security_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Security Scan
        run: ./gradlew spotbugs
        continue-on-error: true

  generate_docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Documentation
        run: ./gradlew dokkaHtml

      - name: Print Documentation Path
        run: echo "Documentation generated in $(pwd)/app/build/dokka/html/index.html"
